export const queryKeys = {
  lead: {
    all: ["lead"] as const,
    list: (params: string) => ["lead", "list", params] as const,
    detail: (id: number) => ["lead", "detail", id] as const,
    references: ["lead", "references"] as const,
    tasks: (leadId: number, params: string) => ["lead", "tasks", leadId, params] as const,
    taskList: (leadId: number) => ["lead", "tasks", leadId] as const,
    assignees: (params: string) => ["lead", "assignees", params] as const,
    products: (params: string) => ["lead", "products", params] as const,
    provinces: (params: string) => ["lead", "provinces", params] as const,
    organizations: (params: string) => ["lead", "organizations", params] as const,
    activities: (leadId: number) => ["lead", "activities", leadId] as const,
    activityStatistics: (leadId: number) => ["lead", "activity-statistics", leadId] as const,
  },
  customer: {
    all: ["customer"] as const,
    list: (params: string) => ["customer", "list", params] as const,
    detail: (id: number) => ["customer", "detail", id] as const,
    count: ["customer", "count"] as const,
    salesUsers: ["customer", "sales-users"] as const,
    addresses: (id: number) => ["customer", "addresses", id] as const,
    contacts: (id: number) => ["customer", "contacts", id] as const,
    opportunities: (id: number) => ["customer", "opportunities", id] as const,
    quotes: (id: number) => ["customer", "quotes", id] as const,
    contracts: (id: number) => ["customer", "contracts", id] as const,
    invoices: (id: number) => ["customer", "invoices", id] as const,
    activities: (id: number) => ["customer", "activities", id] as const,
    feedbacks: (id: number) => ["customer", "feedbacks", id] as const,
    attachments: (id: number) => ["customer", "attachments", id] as const,
  },
};
